# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rooms.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_roomsDialog(object):
    def setupUi(self, roomsDialog):
        roomsDialog.setObjectName("roomsDialog")
        roomsDialog.resize(626, 331)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(roomsDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.middleSplitter = QtWidgets.QSplitter(roomsDialog)
        self.middleSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.middleSplitter.setObjectName("middleSplitter")
        self.roomsFrame = QtWidgets.QGroupBox(self.middleSplitter)
        self.roomsFrame.setObjectName("roomsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.roomsFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.roomsTable = QtWidgets.QTableWidget(self.roomsFrame)
        self.roomsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.roomsTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.roomsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.roomsTable.setShowGrid(True)
        self.roomsTable.setGridStyle(QtCore.Qt.NoPen)
        self.roomsTable.setWordWrap(False)
        self.roomsTable.setObjectName("roomsTable")
        self.roomsTable.setColumnCount(2)
        self.roomsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.roomsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomsTable.setItem(0, 1, item)
        self.verticalLayout.addWidget(self.roomsTable)
        self.groupBox = QtWidgets.QGroupBox(self.roomsFrame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.createButton = QtWidgets.QPushButton(self.groupBox)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout.addWidget(self.createButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.middleSplitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.onlineTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.onlineTable.setEnabled(True)
        self.onlineTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.onlineTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.onlineTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.onlineTable.setShowGrid(True)
        self.onlineTable.setGridStyle(QtCore.Qt.NoPen)
        self.onlineTable.setWordWrap(False)
        self.onlineTable.setRowCount(1)
        self.onlineTable.setObjectName("onlineTable")
        self.onlineTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.onlineTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.onlineTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.onlineTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.onlineTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.onlineTable.setItem(0, 1, item)
        self.verticalLayout_2.addWidget(self.onlineTable)
        self.buttonsRoomLayout = QtWidgets.QHBoxLayout()
        self.buttonsRoomLayout.setObjectName("buttonsRoomLayout")
        self.leaveButton = QtWidgets.QPushButton(self.groupBox_2)
        self.leaveButton.setObjectName("leaveButton")
        self.buttonsRoomLayout.addWidget(self.leaveButton)
        self.joinButton = QtWidgets.QPushButton(self.groupBox_2)
        self.joinButton.setObjectName("joinButton")
        self.buttonsRoomLayout.addWidget(self.joinButton)
        self.verticalLayout_2.addLayout(self.buttonsRoomLayout)
        self.verticalLayout_3.addWidget(self.middleSplitter)

        self.retranslateUi(roomsDialog)
        QtCore.QMetaObject.connectSlotsByName(roomsDialog)

    def retranslateUi(self, roomsDialog):
        _translate = QtCore.QCoreApplication.translate
        roomsDialog.setWindowTitle(_translate("roomsDialog", "Rooms"))
        self.roomsFrame.setTitle(_translate("roomsDialog", "Available Rooms"))
        self.roomsTable.setSortingEnabled(True)
        item = self.roomsTable.verticalHeaderItem(0)
        item.setText(_translate("roomsDialog", "1"))
        item = self.roomsTable.horizontalHeaderItem(0)
        item.setText(_translate("roomsDialog", "Name"))
        item = self.roomsTable.horizontalHeaderItem(1)
        item.setText(_translate("roomsDialog", "Online"))
        __sortingEnabled = self.roomsTable.isSortingEnabled()
        self.roomsTable.setSortingEnabled(False)
        item = self.roomsTable.item(0, 0)
        item.setText(_translate("roomsDialog", "lolzeros"))
        item = self.roomsTable.item(0, 1)
        item.setText(_translate("roomsDialog", "2"))
        self.roomsTable.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("roomsDialog", "Create a room"))
        self.label.setText(_translate("roomsDialog", "Name:"))
        self.createButton.setText(_translate("roomsDialog", "Create"))
        self.groupBox_2.setTitle(_translate("roomsDialog", "Online"))
        self.onlineTable.setSortingEnabled(True)
        item = self.onlineTable.verticalHeaderItem(0)
        item.setText(_translate("roomsDialog", "1"))
        item = self.onlineTable.horizontalHeaderItem(0)
        item.setText(_translate("roomsDialog", "Name"))
        item = self.onlineTable.horizontalHeaderItem(1)
        item.setText(_translate("roomsDialog", "Last seen"))
        __sortingEnabled = self.onlineTable.isSortingEnabled()
        self.onlineTable.setSortingEnabled(False)
        item = self.onlineTable.item(0, 0)
        item.setText(_translate("roomsDialog", "Moas"))
        item = self.onlineTable.item(0, 1)
        item.setText(_translate("roomsDialog", "Thu, 12:45"))
        self.onlineTable.setSortingEnabled(__sortingEnabled)
        self.leaveButton.setText(_translate("roomsDialog", "Leave"))
        self.joinButton.setText(_translate("roomsDialog", "Join"))

